[package]
name = "cuckoo-hash-cli"
version = "0.1.0"
authors = ["Nikita Smelov"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.7"
cuckoo-hash = { path = "../cuckoo-hash" }
